# -*- coding: utf-8 -*-
"""1to10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V5ctowF9AT79jq8-VERXpJrbbRVxjaxO
"""

# Bank account

class BankAccount:
    def __init__(self, name, account_number, balance):
        self.name = name
        self.account_number = account_number
        self.balance = balance


    def info(self):
      print("Name:", self.name)
      print("Account_number:", self.account_number)
      print("Balance:", self.balance)


account1 = BankAccount("Amna", "12345", 3456000)
account2 = BankAccount("Aliya", "00987", 2000000)
account3 = BankAccount("Sumaira", "56000", 67000)


account1.info()

# Student
class Students:
    def __init__(self, name, roll_number, course):
        self.name = name
        self.roll_number = roll_number
        self.course = course


Student1 = Students("Amna", "01", "engineering")
Student2 = Students("Aliya", "02", "computer")
Student3 = Students("Sumaira", "03", "biology")

print(Student1.name, Student1.roll_number, Student1.course)
print(Student2.name, Student2.roll_number, Student2.course)
print(Student3.name, Student3.roll_number, Student3.course)

#  car

class Car:
    def __init__(self, brand, model, color):
        self.brand = brand
        self.model = model
        self.color = color

car1 = Car("Toyota", "Corolla", "White")
car2 = Car("Honda", "Civic", "Black")

print(car1.brand, car1.model, car1.color)
print(car2.brand, car2.model, car2.color)

# phone

class MobilePhone:
    def __init__(self, brand, model, price):
        self.brand = brand
        self.model = model
        self.price = price

phone1 = MobilePhone("Samsung", "S24", 200000)
phone2 = MobilePhone("Vivo", "V30", 100000)

print(phone1.brand, phone1.model, phone1.price)
print(phone2.brand, phone2.model, phone2.price)

#  employee

class Employee:
    def __init__(self, name, ID, department, salary):
        self.name = name
        self.ID = ID
        self.department = department
        self.salary = salary

employee1 = Employee("Ali", 101, "HR", 60000)
employee2 = Employee("Sara", 102, "IT", 80000)

print(employee1.name, employee1.ID, employee1.department, employee1.salary)
print(employee2.name, employee2.ID, employee2.department, employee2.salary)

# book

class Book:
    def __init__(self, title, author, price):
        self.title = title
        self.author = author
        self.price = price

book1 = Book("The Alchemist", "Paulo Coelho", 1500)
book2 = Book("Harry Potter", "J.K. Rowling", 2000)

print(book1.title, book1.author, book1.price)
print(book2.title, book2.author, book2.price)

# order


class Order:
    def __init__(self, customer_name, food_item, quantity):
        self.customer_name = customer_name
        self.food_item = food_item
        self.quantity = quantity

order1 = Order("Ali", "Pizza", 2)
order2 = Order("Sara", "Burger", 3)

print(order1.customer_name, order1.food_item, order1.quantity)
print(order2.customer_name, order2.food_item, order2.quantity)

# patient


class Patient:
    def __init__(self, name, age, disease):
        self.name = name
        self.age = age
        self.disease = disease

patient1 = Patient("Ali", 25, "Fever")
patient2 = Patient("Sara", 30, "Flu")

print(patient1.name, patient1.age, patient1.disease)
print(patient2.name, patient2.age, patient2.disease)

# laptop

class Laptop:
    def __init__(self, brand, RAM, storage, price):
        self.brand = brand
        self.RAM = RAM
        self.storage = storage
        self.price = price

    def info(self):
      print("Brand:", self.brand)
      print("RAM:", self.RAM)
      print("Storage:", self.storage)
      print("Price:", self.price)


l1 = Laptop("Dell", "8GB", "256GB", 100000)
l2 = Laptop("Lenovo", "16GB", "512GB", 150000)



l1.info()

# product

class Product:
    def __init__(self, product_name, category, price, stock_quantity):
        self.product_name = product_name
        self.category = category
        self.price = price
        self.stock_quantity = stock_quantity

product1 = Product("T-Shirt", "Clothing", 2000, 50)
product2 = Product("Shoes", "Footwear", 5000, 20)

print(product1.product_name, product1.category, product1.price, product1.stock_quantity)
print(product2.product_name, product2.category, product2.price, product2.stock_quantity)